# Generated by Django 3.2.12 on 2024-04-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='nom_client',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
