# Generated by Django 3.2.12 on 2024-04-29 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0005_auto_20240429_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0)),
        ),
    ]
