# Generated by Django 3.2.12 on 2024-04-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0006_facture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
