# Generated by Django 3.2.12 on 2024-05-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0008_auto_20240505_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantprofile',
            name='expert_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fin.expertprofile'),
        ),
        migrations.AddField(
            model_name='client',
            name='Expertprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fin.expertprofile'),
        ),
    ]
