# Generated by Django 3.2.12 on 2024-05-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0009_auto_20240506_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fournisseur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dim_Temps',
            fields=[
                ('id_temps', models.AutoField(primary_key=True, serialize=False)),
                ('id_Temps', models.CharField(max_length=500)),
                ('jour', models.CharField(max_length=2)),
                ('mois', models.CharField(max_length=2)),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fait_vente',
            fields=[
                ('id_ligne_facture', models.AutoField(primary_key=True, serialize=False)),
                ('TVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hors_taxe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_client')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_produit')),
                ('id_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_temps')),
            ],
        ),
        migrations.CreateModel(
            name='fait_achat',
            fields=[
                ('id_ligne_facture', models.AutoField(primary_key=True, serialize=False)),
                ('TVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hors_taxe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_fournisseur')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_produit')),
                ('id_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_temps')),
            ],
        ),
    ]
