# Generated by Django 3.2.12 on 2024-05-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0010_dim_client_dim_fournisseur_dim_produit_dim_temps_fait_achat_fait_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fait_achat',
            name='id_fournisseur',
        ),
        migrations.RemoveField(
            model_name='fait_achat',
            name='id_produit',
        ),
        migrations.RemoveField(
            model_name='fait_achat',
            name='id_temps',
        ),
        migrations.RemoveField(
            model_name='fait_vente',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='fait_vente',
            name='id_produit',
        ),
        migrations.RemoveField(
            model_name='fait_vente',
            name='id_temps',
        ),
        migrations.DeleteModel(
            name='Dim_Client',
        ),
        migrations.DeleteModel(
            name='Dim_Fournisseur',
        ),
        migrations.DeleteModel(
            name='Dim_Produit',
        ),
        migrations.DeleteModel(
            name='Dim_Temps',
        ),
        migrations.DeleteModel(
            name='fait_achat',
        ),
        migrations.DeleteModel(
            name='fait_vente',
        ),
    ]
