# Generated by Django 3.2.12 on 2024-05-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0012_dim_produit_dim_temps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fait_vente',
            fields=[
                ('id_ligne_facture', models.AutoField(primary_key=True, serialize=False)),
                ('TVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hors_taxe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_client')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_produit')),
                ('id_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_temps')),
            ],
        ),
    ]
