# Generated by Django 3.2.12 on 2024-05-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0013_dim_client_fait_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fournisseur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fait_achat',
            fields=[
                ('id_ligne_facture', models.AutoField(primary_key=True, serialize=False)),
                ('TVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hors_taxe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_fournisseur')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_produit')),
                ('id_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin.dim_temps')),
            ],
        ),
    ]
