# Generated by Django 3.2.12 on 2024-05-16 16:14

from django.db import migrations, models
import fin.models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0014_dim_fournisseur_fait_achat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_client_ent',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=500, validators=[fin.models.validate_caracteres])),
                ('Adresse', models.CharField(default=' ', max_length=500)),
                ('Activity', models.CharField(default=' ', max_length=500)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
            ],
        ),
    ]
