# Generated by Django 3.2.12 on 2024-05-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0015_dim_client_ent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fait_achat',
            name='client_ent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fin.dim_client_ent'),
        ),
        migrations.AddField(
            model_name='fait_vente',
            name='client_ent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fin.dim_client_ent'),
        ),
    ]
