# Generated by Django 3.2.12 on 2024-05-16 18:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0016_auto_20240516_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='fait_vente',
            name='CA',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
