# Generated by Django 3.2.12 on 2024-05-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0017_fait_vente_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='fait_achat',
            name='id_facture',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fin.dataimport'),
        ),
        migrations.AddField(
            model_name='fait_vente',
            name='id_facture',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fin.dataimport'),
        ),
    ]
