# Generated by Django 3.2.12 on 2024-05-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0018_auto_20240518_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_facture',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('num_fac', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='fait_achat',
            old_name='id_facture',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='fait_vente',
            old_name='id_facture',
            new_name='id_user',
        ),
        migrations.AddField(
            model_name='fait_achat',
            name='id_fact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fin.dim_facture'),
        ),
        migrations.AddField(
            model_name='fait_vente',
            name='id_fact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fin.dim_facture'),
        ),
    ]
